# This is a basic workflow to help you get started with Actions

name: Cloud_Computing_Project_Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CODE_ZIP: "cc_manage_lambda.zip" 
  VAULT_TOKEN: "hvs.Hfkxg6re5QTY8mK7dzibccGB"
  VAULT_URL: "http://54.86.229.209:8200/v1/aws/creds/Admin"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Run a multi-line script
  #       run: |
  #         cd Scripts
  #         sh docker_image_build.sh

  code_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Management lambda build
        run: |
          cd Python/
          python3 package.py
  
      - name: Archive code zip
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CODE_ZIP }}
          path: Python/bin/${{ env.CODE_ZIP }}
  
  terraform_apply:
    runs-on: ubuntu-latest
    needs: code_build
    steps:
      - uses: actions/checkout@v3

      - name: Download workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CODE_ZIP }}

      - name: Terraform apply with 
        run: |
          CREDS=$(curl -H "X-Vault-Token: $VAULT_TOKEN" -X GET $VAULT_URL | jq .data)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq .access_key | sed 's/\"//g' )
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq .secret_key | sed 's/\"//g' )
          export AWS_DEFAULT_REGION=us-east-1
          echo "" > ~/.aws/credentials
          cat <<EOT >> ~/.aws/credentials
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
          EOT
          chmod 600 ~/.aws/credentials
          sleep 10
          mkdir -p Terraform/bin/
          mv ${{ env.CODE_ZIP }} Terraform/bin/
          cd Terraform
          terraform init --reconfigure
          terraform apply --auto-approve

