# This is a basic workflow to help you get started with Actions

name: Cloud_Computing_Project_Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VAULT_TOKEN: "hvs.Hfkxg6re5QTY8mK7dzibccGB"
  VAULT_URL: "http://54.86.229.209:8200/v1/aws/creds/Admin"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Provision AWS Infrastructure
        run: |
          CREDS=$(curl -H "X-Vault-Token: $VAULT_TOKEN" -X GET $VAULT_URL | jq .data)
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq .access_key | sed 's/\"//g' )
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq .secret_key | sed 's/\"//g' )
          export AWS_DEFAULT_REGION=us-east-1
          sleep 10
          cd Terraform
          terraform init --reconfigure
          terraform taint docker_registry_image.cc_app_image
          terraform apply --auto-approve -var VAULT_TOKEN=$VAULT_TOKEN
